os: osx
osx_image:
  - xcode11.2
  - xcode10.3
language: swift
script: 
  # Compile, test, sign, and run using SwiftPM 5.
  - swift build
  - swift test
  - codesign --sign - --verbose .build/debug/idbcl
  - ./.build/debug/idbcl

  # Install and load launchd agent
  - ./.build/debug/idbcl create-launchagent
  - launchctl load ~/Library/LaunchAgents/idbcl.plist

