name: Swift

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-10.14, macOS-10.15]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Run program normally
      run: swift run idbcl update
    - name: Install as agent
      run: |
        swift run -c release idbcl create-launchagent
        # Sign
        codesign -s - -v ./.build/release/idbcl
        # Lint the generated file
        plutil -lint ~/Library/LaunchAgents/idbcl.plist
        # Load without restarting user aqua session
        launchctl load ~/Library/LaunchAgents/idbcl.plist
        launchctl list idbcl
