name: Swift

on: [push]

jobs:
  build:
    runs-on: macOS-latest 
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Run program normally
      run: swift run idbcl update
    - name: Install as agent
      run: |
        swift run -c release idbcl create-launchagent
        # Sign (if required)
        # codesign -s - -v ./.build/release/idbcl
        # Load without restarting user aqua session
        launchctl load ~/Library/LaunchAgents/idbcl.plist
        launchctl list idbcl
